In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("diabetes_012_health_indicators_BRFSS2015.csv")

In [3]:
dataset

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,2.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [6]:
x=dataset.iloc[:,1:].values

In [7]:
x

array([[1., 1., 1., ..., 9., 4., 3.],
       [0., 0., 0., ..., 7., 6., 1.],
       [1., 1., 1., ..., 9., 4., 8.],
       ...,
       [0., 0., 1., ..., 2., 5., 2.],
       [1., 0., 1., ..., 7., 5., 1.],
       [1., 1., 1., ..., 9., 6., 2.]])

In [8]:
y=dataset.iloc[:,0].values

In [9]:
y

array([0., 0., 0., ..., 0., 0., 2.])

In [10]:
from sklearn.decomposition import PCA

In [12]:
pca=PCA(n_components=2)

In [1]:
pca.fit(x)

NameError: name 'pca' is not defined

In [18]:
xx=pca.transform(x)

In [19]:
xx

array([[19.07926789,  7.94225281],
       [-5.4084595 , -2.32445378],
       [35.47543348, -7.29524641],
       ...,
       [-5.16117635,  0.65937352],
       [-5.72686051, -4.25513494],
       [-5.50764172, -2.37072916]])

In [21]:
df_pca1 = pd.DataFrame(xx,
                       columns=['PC{}'.
                       format(i+1)
                        for i in range(2)])

In [22]:
df_pca1

              PC1        PC2
0       19.079268   7.942253
1       -5.408459  -2.324454
2       35.475433  -7.295246
3       -5.379667  -0.462114
4       -4.193144  -3.919073
...           ...        ...
253675   1.635295  16.831240
253676  -6.559798  -9.188122
253677  -5.161176   0.659374
253678  -5.726861  -4.255135
253679  -5.507642  -2.370729

[253680 rows x 2 columns]